_target_: src.models.gcpnet_module.GCPNetLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.00001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.8
  min_lr: 0.00001
  patience: 10
  threshold: 0.0002
 
net:
  _target_: src.models.components.simple_gcpnet.GCPNet
  firstUpdateLayers: 4
  secondUpdateLayers: 4

# compile model for faster training with pytorch 2.0
compile: false
